name: Run lint-md
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install lint-md-cli
      run: npm i lint-md-cli
    - name: lint-md check
      run: ./node_modules/.bin/lint-md ./docs --config mdlint.json
